### ISSUE TITLE
Add command handler

### ISSUE THREAD

**Issue by apoorvcodes** [kavin25/discord-task-bot#14]
**Is your feature request related to a problem? Please describe.**
Dude the code itself looks super unmanged , add a command handler and event handler

**Describe the solution you'd like**
I'll make a custom command handler and port over every single stuff to it

**Describe alternatives you've considered**
Use of wok command can quick the process but isnt that credible

**Comment by apoorvcodes** [comment]
I'll like to do this stuff u can assign me this

**Comment by kavinvalli** [comment]
@apoorvcodes Sure, go ahead

**Comment by kavinvalli** [comment]
Fixed by #15
